### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by jaypatil** [PacktPublishing/Building-Web-Apps-with-Spring-5-and-Angular#1]
Information:java: Errors occurred while compiling module 'healthapp'
Information:javac 1.8.0_152 was used to compile java sources
Information:9/1/18 12:42 PM - Compilation completed with 3 errors and 2 warnings in 6s 571ms
/home/lumium/Downloads/BuildingWebAppswithSpring5andAngular_Code/HealthApp_Spring-source-code/src/main/java/com/book/healthapp/repositories/UserDAOImpl.java
Warning:(7, 21) java: org.hibernate.Query in org.hibernate has been deprecated
/home/lumium/Downloads/BuildingWebAppswithSpring5andAngular_Code/HealthApp_Spring-source-code/src/main/java/com/book/healthapp/configuration/AppConfig.java
Error:(9, 51) java: cannot find symbol
  symbol:   class DataSourceBuilder
  location: package org.springframework.boot.autoconfigure.jdbc
Warning:(30, 57) java: org.springframework.web.servlet.config.annotation.WebMvcConfigurerAdapter in org.springframework.web.servlet.config.annotation has been deprecated
Error:(54, 37) java: cannot find symbol
  symbol:   variable DataSourceBuilder
  location: class com.book.healthapp.configuration.AppConfig
/home/lumium/Downloads/BuildingWebAppswithSpring5andAngular_Code/HealthApp_Spring-source-code/src/main/java/com/book/healthapp/configuration/SecurityConfiguration.java
Error:(19, 26) java: cannot find symbol
  symbol:   variable ACCESS_OVERRIDE_ORDER
  location: class org.springframework.boot.autoconfigure.security.SecurityProperties
/home/lumium/Downloads/BuildingWebAppswithSpring5andAngular_Code/HealthApp_Spring-source-code/src/main/java/com/book/healthapp/repositories/RxDAOImpl.java
Information:java: Some input files use unchecked or unsafe operations.
Information:java: Recompile with -Xlint:unchecked for details.

**Comment by gabrielgaroz** [comment]
Hello. I'm having the same issue. How did you fix it?

**Comment by shubham763** [comment]
Please reopen if the issue still persists.
